; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32s3mini_ota

[env:esp32s3mini]
platform = espressif32
board = esp32-s3-devkitc1-n4r2
framework = arduino
monitor_speed = 115200

upload_port = COM27
monitor_port = COM27

board_build.filesystem = spiffs
board_build.partitions = partitions/default.csv
extra_scripts = pre:scripts/generate_build_info.py
lib_deps =
	knolleary/PubSubClient @ ^2.8
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson @ ^7.0.4
	adafruit/Adafruit NeoPixel @ ^1.12.0
build_flags =
	-std=c++2a
	-DBOARD_HAS_PSRAM

[env:esp32s3mini_ota]
platform = espressif32
board = esp32-s3-devkitc1-n4r2
framework = arduino

upload_protocol = espota
upload_port = renovent.local

board_build.filesystem = spiffs
board_build.partitions = partitions/default.csv
extra_scripts = pre:scripts/generate_build_info.py
lib_deps =
	knolleary/PubSubClient @ ^2.8
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson @ ^7.0.4
	adafruit/Adafruit NeoPixel @ ^1.12.0
build_flags =
	-std=c++2a
	-DBOARD_HAS_PSRAM
upload_flags =
	--auth=Rnv8x3Qp7Lk2Zm5H